name = "AutoAligns"
uuid = "d725926e-c28a-11e8-0b27-a9b7192b898d"
authors = ["Mark Hildebrand <mhildebrand@ucdavis.edu>"]
version = "0.1.0"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
